#include "tests.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "solve_equation.h"
#include "parser.h"
#include "config.h"

static const struct ParserTestCase test_cases[] = {
    {.num = 1,
     .s = "2x^2 + 3x + 1 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 2,
     .s = "x^2 + x + 1 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 1,
                  .b = 1,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 3,
     .s = "-x^2 - x - 1 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = -1,
                  .b = -1,
                  .c = -1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 4,
     .s = "5x^2 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 5,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 5,
     .s = "3x + 2 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 3,
                  .c = 2,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 6,
     .s = "7 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 7,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 7,
     .s = "x^2 = 2x^2 + 3x + 4",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = -1,
                  .b = -3,
                  .c = -4,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 8,
     .s = "2x^2 + 3x + 1 = 2x^2 + 3x + 1",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 9,
     .s = "1.5x^2 + 2.7x + 3.9 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 1.5,
                  .b = 2.7,
                  .c = 3.9,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 10,
     .s = "-2.5x^2 - 3.5x - 4.5 = 1.5x^2 + 2.5x + 3.5",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = -4,
                  .b = -6,
                  .c = -8,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 11,
     .s = "x^2 + 1 = 2x^2 + 3",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = -1,
                  .b = 0,
                  .c = -2,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 12,
     .s = "0x^2 + 0x + 0 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 13,
     .s = "10x^2 - 20x + 30 = 5x^2 + 10x - 15",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 5,
                  .b = -30,
                  .c = 45,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 14,
     .s = "x^2 = x^2",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 15,
     .s = "x = x",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 16,
     .s = "0 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 17,
     .s = "2.5x^2 = 1.5x^2 + 2x + 3",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 1,
                  .b = -2,
                  .c = -3,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 18,
     .s = "x^2 + 2x + 1 = x^2 + 2x + 1",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},

    {.num = 19,
     .s = "2x^2 + 3x + 1",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 20,
     .s = "2x^2 + 3x + 1 = 0 = 5",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 21,
     .s = "2*x^2 + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 22,
     .s = "2x^2 + 3x + 1 = 0x",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 23,
     .s = "2x^2 + 3x + 1 = ",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 24,
     .s = "2x^2 + 3x + 1 = abc",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 25,
     .s = "",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 26,
     .s = "2x^3 + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 27,
     .s = "2x^2 + 3y + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 28,
     .s = "2x^ + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 29,
     .s = "2x^2 + + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 30,
     .s = "2x^2 + 3x + 1 = 0 +",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 31,
     .s = "2x^2 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 32,
     .s = "x^2.5 + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 33,
     .s = "2.5.7x^2 + 3x + 1 = 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 34,
     .s = "2x^2 + 3x + 1 = 0 5",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 35,
     .s = "x + x^2 + x^2 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 1,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 36,
     .s = "2x^2 + 3x + 1 = 2x^2 +",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 37,
     .s = "= 2x^2 + 3x + 1",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 38,
     .s = "2x^2 + 3x + 1 == 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 39,
     .s = "2x^2 + 3x + 1 = 0;",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 40,
     .s = "2x^2 + 3x + 1 = 0\n",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 41,
     .s = "x^2 = x^2 + x^2",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = -1,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 42,
     .s = "2x^2 + 3x + 1 = 2x^2 + 3x + 1 +",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 43,
     .s = "2x^2 + 3x + 1 = 0 -",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 44,
     .s = "2x^2 + 3x + 1 = 0 0",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 45,
     .s = "x^2 + x^2 = 2x^2",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 46,
     .s = " ",
     .is_correct_format = 0,
     .is_correct_parse = 0,
     .equation = {.a = 0,
                  .b = 0,
                  .c = 0,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 47,
     .s = "2x^2 + 3x + 1 = 0 ",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 48,
     .s = " 2x^2 + 3x + 1 = 0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 49,
     .s = "2x^2+3x+1=0",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 2,
                  .b = 3,
                  .c = 1,
                  .n_roots = NO_REAL_ROOTS}},
    {.num = 50,
     .s = "2x^2 - 3x + 1 = x^2 + x - 2",
     .is_correct_format = 1,
     .is_correct_parse = 1,
     .equation = {.a = 1,
                  .b = -4,
                  .c = 3,
                  .n_roots = NO_REAL_ROOTS}},
};

static const char *get_success_str(int is_correct)
{
    return is_correct ? "successful parsing" : "failed parsing";
}

static int run_test(struct ParserTestCase test_case)
{
    char *s = (char *)calloc(strlen(test_case.s) + 1, sizeof(char));
    strcpy(s, test_case.s);
    struct Parser parser = init_parser(s);

    if (parser.is_correct_format != test_case.is_correct_format)
    {
        printf(RED_C "Parser test %d FAILED\n"
                     "String: %s\n"
                     "Expected: parser.is_correct_format=%d\n"
                     "Got:      parser.is_correct_format=%d\n" RESET_C,
               test_case.num, test_case.s, test_case.is_correct_format, parser.is_correct_format);
        free(s);
        return 0;
    }

    struct QuadraticEquation eq = {.n_roots = NO_REAL_ROOTS};
    int is_correct_parse = parser.parse(&parser, &eq);

    if (is_correct_parse != test_case.is_correct_parse)
    {
        printf(RED_C "Parser test %d FAILED\n"
                     "String: %s\n"
                     "Expected: %s\n"
                     "Got:      %s\n" RESET_C,
               test_case.num, test_case.s,
               get_success_str(test_case.is_correct_parse),
               get_success_str(is_correct_parse));
        free(s);
        return 0;
    }

    if (d_is_equal(eq.a, test_case.equation.a) && d_is_equal(eq.b, test_case.equation.b) && d_is_equal(eq.b, test_case.equation.b))
    {
        printf(GREEN_C "Parser test %d passed!\n" RESET_C, test_case.num);
        free(s);
        return 1;
    }
    printf(RED_C "Parser test %d FAILED\n"
                 "String: %s\n"
                 "Expected: a=%lg, b=%lg, c=%lg\n"
                 "Got:      a=%lg, b=%lg, c=%lg\n" RESET_C,
           test_case.num, test_case.s,
           test_case.equation.a, test_case.equation.b, test_case.equation.c,
           eq.a, eq.b, eq.c);
    free(s);
    return 0;
}

int run_parser_tests(void)
{
    int passed = 0;
    int test_count = sizeof test_cases / sizeof(struct ParserTestCase);

    printf("Start parser testing\n");

    for (int i = 0; i < test_count; i++)
        passed += run_test(test_cases[i]);

    int are_all_passed = passed == test_count;

    printf("End parser testing\n");
    printf("%sPassed: %d/%d tests\n\n%s",
           are_all_passed ? "\x1b[32m" : "\x1b[31m",
           passed, test_count,
           "\x1b[0m");

    return are_all_passed;
}