name: CI Workflow

on:
  push:
    branches: [main, test]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: latest
          platform: x64

      - run: sudo apt update

      # - name: Set up OpenGL
      #   run: sudo apt install libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev

      - name: Install Raylib
        run: sudo apt-get install -y libraylib-dev libgl1-mesa-dev libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev

      - name: Compile and run tests
        run: ./compile.sh
